### ISSUE TITLE
Integer IDs are not supported

### ISSUE THREAD

**Issue by jdbaldry** [chronly/jsonrpc2#2]
From https://www.jsonrpc.org/specification
> id
An identifier established by the Client that MUST contain a String, Number, or NULL value if included. If it is not included it is assumed to be a notification. The value SHOULD normally not be Null [1] and Numbers SHOULD NOT contain fractional parts [2]

**Comment by rfratto** [comment]
Thanks for pointing this out! Working on a fix now.
